package com.claude.web.dto;

import org.junit.jupiter.api.Test;

import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

/**
 * NotificationEvent 单元测试
 */
class NotificationEventTest {

    @Test
    void testDefaultConstructor() {
        NotificationEvent event = new NotificationEvent();
        assertNull(event.getMethod());
        assertNull(event.getParams());
        assertNull(event.getAtIso());
    }

    @Test
    void testParameterizedConstructor() {
        NotificationEvent event = new NotificationEvent("test/method", Map.of("key", "value"));
        assertEquals("test/method", event.getMethod());
        assertNotNull(event.getParams());
        assertNotNull(event.getAtIso());
    }

    @Test
    void testSettersAndGetters() {
        NotificationEvent event = new NotificationEvent();
        event.setMethod("stream_delta");
        event.setParams(Map.of("content", "hello"));
        event.setAtIso("2024-01-01T00:00:00Z");

        assertEquals("stream_delta", event.getMethod());
        assertEquals("2024-01-01T00:00:00Z", event.getAtIso());
    }

    @Test
    void testAtIsoIsAutoGenerated() {
        NotificationEvent event = new NotificationEvent("test", null);
        assertNotNull(event.getAtIso());
        assertFalse(event.getAtIso().isEmpty());
    }

    @Test
    void testNullParams() {
        NotificationEvent event = new NotificationEvent("ping", null);
        assertEquals("ping", event.getMethod());
        assertNull(event.getParams());
    }
}
