server:
  port: 8080

spring:
  application:
    name: claude-web
  web:
    resources:
      cache:
        period: 0
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.224.56.231:3306/codex?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: codex
    password: code@1762!#

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.claude.web.entity
  configuration:
    map-underscore-to-camel-case: true

file:
  upload:
    dir: ./uploads

claude:
  model: GLM-4.7-AWQ
  web:
    password: 111
    password-enabled: true
    auto-approve: true
    claude-agent:
      host: 47.116.75.73
      port: 8010
      api-key: 204e28ff45370960b6649057352f00c96a60c34ad9fa47defed2436a3e5762c29761a078fbd183b1ea831d048d48736986ecfbf28999ac0369ab7c8f639f0b0d
      connection-timeout: 30000

logging:
  config: classpath:logback-spring.xml
  level:
    com.claude.web: INFO
    org.springframework.security: INFO
